server:
  port: 8080
  environment: "development" # development, production

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "securepassword"
  dbname: "interface_logs"
  sslmode: "disable"

apigee:
  auth_url: "https://t2-dev.dn-apigw.gtm.iplab.au.singtelgroup.net/oauth/v1/accesstoken"
  client_id: "system"
  client_secret: "manager"

downstreams:
#3cdil:
#  [cite_start]host: "http://10.197.77.26:443" # [cite: 48]
#  [cite_start]base_path: "/crimson/ar/v1" # [cite: 48]
# [cite_start]timeout_ms: 400 #

eda2:
  host: "http://eda2-host:443"
  base_path: "/eda2/v1"
  timeout_ms: 500







